{
 "title": "DigitalTwinDB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Info sur le Raspberry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "On / Off",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "etat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Localisation Raspberry",
   "type": "grafana-worldmap-panel",
   "description": "Carte indiquant la localisation du Raspberry ",
   "gridPos": { "h": 22, "w": 13, "x": 8, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "measurement": "coordonnees",
     "select": [
      [
       { "params": [ "geo" ], "type": "field" }
      ],
      [
       { "params": [ "metric" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Image d'un Raspberry pi",
   "type": "text",
   "description": "Image d'un Raspberry pi avec un Sense hat b",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 9 },
   "options": {
    "content": "\n\n<img src=/public/img/RPISENSE.png>"
   }
  },
  { "title": "Metriques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Pression",
   "type": "stat",
   "description": "Pression en temps réel",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pression",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "gauge",
   "description": "Humidité en temps réel.",
   "gridPos": { "h": 5, "w": 10, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pression",
   "type": "timeseries",
   "description": "Pression en temps réel.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pression",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "description": "Historique de l'humidité.",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidite",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Température ",
   "type": "bargauge",
   "description": "Température en temps réel. ",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Température ",
   "type": "timeseries",
   "description": "Historique des température. ",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}